import ROOT as rt

rootpath="."
name="bkg_eff2018"
year="2018"
rt.gStyle.SetPaintTextFormat(".2f")
rt.gStyle.SetOptStat(0)
finmc = rt.TFile("{}/{}.root".format(rootpath,name))
c1=rt.TCanvas()
c1.Draw()
hup_b= finmc.Get("btag_passwp_b_"+year)
hdown_b= finmc.Get("btag_b_"+year)
hup_c= finmc.Get("btag_passwp_c_"+year)
hdown_c= finmc.Get("btag_c_"+year)
hup_light= finmc.Get("btag_passwp_light_"+year)
hdown_light= finmc.Get("btag_light_"+year)
hup_b.Sumw2()
hdown_b.Sumw2()
hup_c.Sumw2()
hdown_c.Sumw2()
hup_light.Sumw2()
hdown_light.Sumw2()
hup_b.Rebin2D(2,4)
hdown_b.Rebin2D(2,4)
hup_c.Rebin2D(2,4)
hdown_c.Rebin2D(2,4)
hup_light.Rebin2D(2,4)
hdown_light.Rebin2D(2,4)
c1.SetLogx()
h_eff_b=hup_b.Clone("h_eff_b")
print h_eff_b.Integral()
h_eff_b.Divide(hdown_b)
print h_eff_b.Integral()
h_eff_b.SetTitle("btag_eff_b ;p_{T};#eta")
h_eff_b.Draw("text COL error")
c1.SaveAs("h_eff_b_"+year+".pdf")


h_eff_c=hup_c.Clone("h_eff_c")
h_eff_c.Divide(hdown_c)
h_eff_c.SetTitle("btag_eff_c ;p_{T};#eta")
h_eff_c.Draw("text COL error")
c1.SaveAs("h_eff_c_"+year+".pdf")

h_eff_light=hup_light.Clone("h_eff_light")
h_eff_light.Divide(hdown_light)
h_eff_light.SetTitle(" btag_eff_light ;p_{T};#eta")
h_eff_light.Draw("text COL error")
c1.SaveAs("h_eff_light_"+year+".pdf")
fout = rt.TFile("{}/{}.root".format(rootpath,"btag_eff_"+year),"recreate")
h_eff_b.Write()
h_eff_c.Write()
h_eff_light.Write()
fout.Close()
finmc.Close()
